### ISSUE TITLE
RFI Data Table Slightly Skewed

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1253]
I was bug-checking the RFI process and noticed the data table looks skewed laterally. There's a half-empty cell right before the "ID" cell and the "Updated" cell at the end looks cut short. What do you guys think is causing this?

![RFI DATA TABLE](https://user-images.githubusercontent.com/85491794/145797115-c9d56fbd-275f-471b-bce7-56cbba4be222.png)

![RFI DATA TABLE 2](https://user-images.githubusercontent.com/85491794/145797160-12075c0d-3d4e-4a9c-b249-779a41548d9a.png)

I also noticed that we are presenting two RFI channels, namely RFI and RFI 2. What distinguishes them from each other?
![2 Blue RFIs](https://user-images.githubusercontent.com/85491794/145797286-73e9d5f0-f2f2-4200-a837-c7abdaad159c.png)

**Comment by ShendMikullovci** [comment]
This is also present in the COA data table:
![COA Data Table](https://user-images.githubusercontent.com/85491794/145803263-e9c8d235-5a10-47ff-8bb2-011ce339806e.png)

**Comment by IanMayo** [comment]
`BLUE COA` and `BLUE COA 2`.  I/we are currently developing Version 3 of Collaborative Editing.  `BLUE COA` is V2, and `BLUE COA 2` is V3.  I was difficult to modify the v2 channel to v3 - it was more robust to create a new one, that's v3 from the start. That's why we have Blue COA channels in the old & new formats. `BLUE COA` will be deleted soon.

**Comment by IanMayo** [comment]
I propose we investigate this once we've got V3 of collaborative working in place.

**Comment by ShendMikullovci** [comment]
This has been fixed.
