### ISSUE TITLE
Color Chart Drag Option

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1262]
The color chart under Forces in the Admin Page is not fully functional. I can't drag the color cursor to a selected shade. Wherever I first click on the chart, that color is selected.

![Color Chart Drag Option](https://user-images.githubusercontent.com/85491794/145841970-22267a9d-105f-4d8a-8c75-4749defe90b8.png)

If we wish to provide this high level of color selection, the user should be able to drag the color cursor across different shades.

However, I don't really think that'll be necessary (unless the client asked for it). The main color shades given right under the chart should suffice. In that case, a simpler design would look like this: 

![Color Chart UX Design](https://user-images.githubusercontent.com/85491794/145841816-c9ed09f7-8ba3-4996-a1cb-96318a3a2513.png)

Let me know your thoughts.

**Comment by IanMayo** [comment]
Sure, good thinking @ShendMikullovci 

My first thought is that just need to change how we configure the editor.  But - I agree with you, a color selector should be sufficient.

@lebaphi - could you investigate providing a simpler color menu picker please?

IMHO the `Block` style of dialog should be sufficient.  Note:  I think we should keep a HTML/RGB free-text editor option, since the _real_ force genuinely may have its own color.

Note: it looks like [this](https://casesandberg.github.io/react-color/#api-onChange) is the color checker we're using.

**Comment by ShendMikullovci** [comment]
This has been fixed.
