### ISSUE TITLE
Distinguishing Channel Types

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1284]
We should work on distinguishing the channel types. The user might get confused and not realize they are editing the wrong channel. 
I suggest that when the user clicks on a new mapping channel, the default title should be "New Mapping Channel".

Same for Collab Edit' and Collab Response.

Not a very costly change and should help the user navigate the page more efficiently.

**Comment by ShendMikullovci** [comment]
Question: What is a "Special Channel"?

**Comment by IanMayo** [comment]
As far as I can imagine, there will only ever be one channel titled `Mapping`.

For `Collab Edit` and `Collab Response` the channel name is expected to be the business process that the channel implements, so it's `Blue COA` or `Blue RFI`.

A `Special channel` is one other than the `Standard` channel (that just takes a series of participations, with templates).

In the medium term I aim to introduce a `New > Chat channel`. This will be another `special` channel, which won't require templates to be specified.

Aah, the `Mapping` channel will also get its own UI, where templates don't need to be specified, but where it indicates which participation(s) are allowed to submit orders.  This moves the `Submit Orders` logic out of `Role`, which is good, because it is unique to mapping.
