### ISSUE TITLE
Channel Tabs

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1285]
Mapping Channel shows a different tab from the 2 other channel tabs.
Here's the Mapping Channel Tab: 

![Mapping Channel Tab](https://user-images.githubusercontent.com/85491794/147100464-17a895d7-4b48-4a80-9e81-075116cc1f07.png)

In Collab Edit' and Collab response, we provide the option to add more forces/roles alongside the default White force:

![Collab Edit' and Response tab](https://user-images.githubusercontent.com/85491794/147100341-09e7b506-eded-492b-ba93-38a330b7643d.png)

Does that suggest that the White force is always included in collab working? 
Does it suggest that the white force might not be included in mapping?

I suggest we provide the same tab for all three.

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - I _think_ they both have the same UI.  When a channel is added, it has an editable "Participation" row shown.  That's why the "refresh/tick" icons are shown.  Since White is the first force created in a default wargame, it's the item shown by default on the drop-down.

So. we don't force the presence of White in any channel - it's just the first item shown when an editable drop-down is collapsed.

**Comment by ShendMikullovci** [comment]
Great. In that case, I suggest we follow the display of the Mapping Channel tab to maintain uniformity.

**Comment by ShendMikullovci** [comment]
They're now identical.
