### ISSUE TITLE
Cluttered data CMDKW-HIGH DATA 

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1304]
I think we should present the subsections of a COA as an ordered list because the user can quickly lose track of what they're reading.

Mainly, the subsections here: 

![Create New Line for Each Section](https://user-images.githubusercontent.com/85491794/149668116-74fdd3a7-25c0-4f4f-8d89-850c10d4524c.png)

Alternatively, we could show them like: 
TURN NUMBER: ---------------
OVERALL INTENTIONS: ---------------
UNIT: ---------------
TASKING: ---------------
SEARCH POLICY: ---------------
ACTION ON CONTACT: ---------------
ANY OTHER POLICY: ---------------

**Comment by IanMayo** [comment]
Nice thinking.
An alternate approach that I've been considering is to render them using a read-only version of the form editor, like we do in the collaborative working channels.  They take up quite a lot more space, and increase a minor performance burden (since it can take longer to lay out the form), but when the Game Designer puts in effort to design the form, we get to re-use that effort when reading the messages.

**Comment by ShendMikullovci** [comment]
This too sounds like a valuable change.
