### ISSUE TITLE
Copy, Duplicate & Select Features

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1412]
In an effort to make a wargame for #1400, I realized a couple of things: 

1. For a game that requires a large number of forces (as well as platforms & assets), we could largely improve the UX for the GC by adding a Copy and Duplicate feature. Here's how it would essentially look:

![Duplicate Feature Idea](https://user-images.githubusercontent.com/85491794/158081504-f865443f-9567-44b1-af53-da0f9484e47a.png)

As the mouse hovers over the platform, we get a "..." button next to the garbage bin. Clicking on it opens a dropdown list with Copy & Duplicate as optional features. Here, clicking on Copy would create a new platform with the same TITLE followed by a "(2)" to avoid confusion, and the same ICON (in case the user wishes to create 2 or more platforms for the same Force with the same name and icon but different variables). On the other hand, clicking on duplicate creates a new platform fully identical to the original one, with identical variables and with a "(2)" following the title. It should allow the GC to quickly add a big number of forces, platforms (and even channels, if we decide to add it there).

2. As I encountered the various bugs I've listed in our issue list, I realized that having the possibility to delete multiple platforms would be very useful. Having to click on the bin, then confirm the deletion every time, for a higher number of elements, takes a very long time for a task as simple. If we could add a Select feature, where the user could select and delete multiple channels, that would eliminate this problem. Here's how it would look:

![Select Feature](https://user-images.githubusercontent.com/85491794/158081715-a46cafb4-f8d9-4613-a9c8-30eb777726fa.png)

Once a platform is selected, the small squares to the left of each platform appear, giving the possibility to select more of them. Also, next to the Create button (view #1396 for my opinion on this particular button and more) a bin button appears as well as the usual "Select All" checkbox. Clicking on the bin would delete the selected platform. Clicking on select all would obviously select all the platforms available, making it easier to delete them by group.

P.S. I also thought about a selection-and-multiple-duplication feature, but I don't know how relevant that would be for our client. 

Let me know what you guys think.

**Comment by IanMayo** [comment]
Thanks for that @ShendMikullovci 

Last things first:  I don't think we need to support bulk-delete.  The Game Designer puts a lot of effort into designing platforms, I think it will be fairly rare that they delete them.

For this coming wargame, it's the large number of `Forces` that we need to think about.  I'm sure the Game Designer will wish to duplicate forces - good suggestion.  They may also wish to duplicate platform-type, since a lot of effort goes into defining a platform-type. 

But, I have trouble separating `Copy` and `Duplicate` (note: for `copy` the game designer may be expecting a `paste` operation.  I don't expect the Game Designer to understand the difference between these two.  So, let's try and think of an action that works for both `platform-type` and `force`.

We could show `Duplicate` icon (`clone` - see below) alongside the `delete` icon for the items in the list of `platform-types`, `forces` and channels. 

It performs this duplicate operation:
* platform-types:  full copy of platform type, but with counter added to end of platform-type-name
* force: full copy of force & assets.  Counter added to force name. Uniq ids for force & assets generated.  Asset names unchanged.
* channel: full copy of channel & participants.  New uniq ids for channel & subscription id's.  Counter added to channel name.

`clone` icon:
![image](https://user-images.githubusercontent.com/1108513/158162524-2117c6b5-bb9a-429f-b8ee-7399aa978ac4.png)

**Comment by ShendMikullovci** [comment]
Love the clone icon. 

> I don't think we need to support bulk-delete. The Game Designer puts a lot of effort into designing platforms, I think it will be fairly rare that they delete them.

Excellent. We eliminate the dropdown entirely. 

> We could show `Duplicate` icon (`clone` - see below) alongside the `delete` icon for the items in the list of `platform-types`, `forces` and channels.
> 
> It performs this duplicate operation:
> 
> * platform-types:  full copy of platform type, but with counter added to end of platform-type-name
> * force: full copy of force & assets.  Counter added to force name. Uniq ids for force & assets generated.  Asset names unchanged.
> * channel: full copy of channel & participants.  New uniq ids for channel & subscription id's.  Counter added to channel name.

Here's how that would look: 

![Clone Feature](https://user-images.githubusercontent.com/85491794/158190162-19cd0b00-0b28-42b0-8cb1-c03cab2611f5.png)

Much simpler, cleaner look with only the clone icon showing next to the bin when the mouse hovers over the element.

**Comment by IanMayo** [comment]
Support this improvement. Giving it relatively low priority - since it's a convenience for the Game Designer.

**Comment by IanMayo** [comment]
@lilitkarapetyan  - could you include "clone" for forces too, please.  Note: this will have to copy all of the roles in the force, but remember to create new (unique) role id's.

**Comment by ShendMikullovci** [comment]
This has been implemented.
