### ISSUE TITLE
Line Spacing Bug Collab Editing

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1415]
It appears the line spacing is not the same for the Release tab compared to Approve and Request Changes: 

![Release Term Line Spacing](https://user-images.githubusercontent.com/85491794/158083023-3fabc048-b157-4092-9332-b65dcc4d5a7d.png)

Could we add a single space there?

**Comment by lebaphi** [comment]
Hi @ShendMikullovci @IanMayo, I think it's not a bug. Because these drop-down menus support multiple items, you can click on the blank line below `chip` and enter anything you want. Actually it should have the same line but the element width is limited so it will break to a newline.

https://user-images.githubusercontent.com/26705621/158833853-fb0660e0-f582-4c1b-9ae9-ed374c13f3fc.mov

**Comment by ShendMikullovci** [comment]
Hi @lebaphi ! Is it possible to have them look identical? It's important for the user to see them the same way when they land on this page, as we want to maintain uniformity.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci - we're down in the depths of the Game Admin pages here.  I'm pretty relaxed about cosmetics in here, compared to the player interface.

Could you record this alignment as a separate issue please?  The description can be fairly brief - your screenshot shows the issue clearly.  That will stop it falling through the cracks, but it'll be a fairly low priority.
