### ISSUE TITLE
Heroku bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1475]
Heroku might be down: 

https://user-images.githubusercontent.com/85491794/161152949-da466266-033a-40c8-a8a7-d44bda44dc92.mp4

This happened after I created a New Wargame and tried to go back to delete it.

**Comment by IanMayo** [comment]
Thanks - this is reproducible.  I strongly suspect that the problem is that the IBM database is down.  As you may know, Heroku is hosting the Serge app, but it wipes the database after every hour or so of un-use. 

So, we're storing the wargames in a database hosted by IBM.  From looking at the `Network` tab in `Chrome dev tools` it looks like all database requests are being denied. See below.

We're currently exploring _yet-another_ database hosting solution, so our reliance on IBM will _probably_ go away.

![image](https://user-images.githubusercontent.com/1108513/161241439-ea6bd75b-97be-49b2-b07a-dafd7520d4da.png)

**Comment by ShendMikullovci** [comment]
This seems to have been fixed.
