### ISSUE TITLE
New asset styling, for info markers.

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1516]
We are going to have one "pool" of SVG markers.  But, we need to give different styling to `map icons` and `info markers`.  Here the left-hand question mark is an `info marker`.

![image](https://user-images.githubusercontent.com/1108513/164017041-783a83a2-7754-469b-a2af-fa216fccb528.png)

I propose we introduce a new styling for info markers:
- force-shade colors, as present
- white filled circle, with outer circle and icon SVG in force color

Here are mockups:
![image](https://user-images.githubusercontent.com/1108513/164020707-51962ead-c341-46ad-bb91-4f30a5a39ec2.png)

I only expect to see changes to the `<InfoMarker>` class.

**Comment by ShendMikullovci** [comment]
Hi Ian! I like the idea of the outlined icons. However, I was looking at our current mapping channels and I think the shape of our markers is going to have to change in order to stick out from the assets. Circles could be problematic, especially since we'll also use colors for the markers themselves. They may easily be confused. 

I found the following icons that might be interesting to consider: 

![Pin Question Mark Icon](https://user-images.githubusercontent.com/85491794/164539464-c885af5a-fa3f-496d-86bf-0b04bd0b3932.png)

I liked this one since it brings us back to the idea of the "pin" marker. The question mark is also widely associated to features related to help, information, and knowledge. 

I also found the exclamation point version: 

![Pin Exclamation Point](https://user-images.githubusercontent.com/85491794/164539729-21d2fcd6-6233-4ba5-80ea-03351b3c9cf2.png)

Depending on how we want to present these markers, this one could also work. It has a more immediate pull due to the association of the exclamation point with urgency, caution, or danger. It could also distinguish it from the unknown assets that we show with a question mark. 

What do you think?

**Comment by IanMayo** [comment]
Nice thinking @ShendMikullovci   Good suggestion.   Essentially, it's just about getting an SVG shape for the eye-drop, then drawing the custom marker over the top.

It does introduce one issue. For our circles, the "origin" for the marker is the centre of the circle. So, the circle is drawn at the centre of the shape.  But, the standard origin for the eye-drop is the bottom point.  This introduces some maths that we've struggled with in the past.

I'm sure it's solve-able, but it's a complication I don't want to get distracted with right now.

So, I support the request, but am marking it as low-priority for now.
