### ISSUE TITLE
Force Admin page needs to include `controls` - UX

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1560]
Sometimes players of one force control assets from another force.

An example of this is when the Game Control is responsible for merchant shipping, or even the red force assets.

This is handled through the `controlledBy` array.  

[**Note:** this shouldn't be an array. It should be a single value.  Only one force can control the assets of another force]

So, in the `Force` page we need this data to be edited.  This should be through providing a drop-down list of the _other_ force-names.  We store the `Force['uniqid']`

So, we could do with an updated design for the `Force` admin page.

**Comment by ShendMikullovci** [comment]
I'm not sure I understand the request. Would you like to present who controls what asset in the Forces page?

**Comment by IanMayo** [comment]
Sure, it's a niche requirement that we probably haven't discussed.

For one large wargame there was a GREEN force. This represented merchant shipping in an ocean.  But, there were no GREEN players.  Instead, the Game Control (umpire) drove those ships.  Instead of making Game Control log in as a green player, each `Force` can have an optional `Controlled By` field. This can (optionally) contain the name of another force (`umpire force`) in this case.  When there is a value - Serge knows to give control to the relevant people in that force.

For the asset-level control, this actually happens in the `Channel` editor for the `mapping channel`.  There is where we pull together roles, assets, and permissions.  It is currently being developed.

**Comment by ShendMikullovci** [comment]
Essentially, we want to give the GC an easier access to asset control through the channel page, if I understand correctly?

If so, here's an idea: 

![Asset Control Feature](https://user-images.githubusercontent.com/85491794/169829905-813b3b5f-55a8-42a3-b7f9-292766e3a88c.png)

We add a column for the asset control of every force. We give the user the option to select which roles among the force would be able to control assets, as well as an overall GC option. Multiple selection.

![Asset Control Feature 2](https://user-images.githubusercontent.com/85491794/169830438-1ba2fe4c-58a1-4cac-80b8-bea09f6892b6.png)

With this feature, we'd also give the user the possibility of assigning specific assets to specific roles if necessary. 

Is this what you had in mind?

**Comment by IanMayo** [comment]
I _was_ expecting the control to go into the `Forces` tab.  So, on the `Green` force page, it would have `Controlled by` with a drop-down value of `Umpire` force.

But yes - you're right.  We _could_ handle it in the `mapping channel` page of the `Channels` tab.

As you've seen the editor currently just allows access restriction to be set:
![image](https://user-images.githubusercontent.com/1108513/169836045-97bf7a48-64a4-4f50-9265-5dabffaca53f.png)

We're half-way through letting different roles in a force control different assets  #1531.  For the second part of that, we need to add a "controls" drop-down, which is a drop-down of the assets in that force, plus "Controls none" and "Controls all".  We _could_ modify that list to include assets from other forces, plus `Controls all (Blue-1)`, `Controls all (Green)`, and so on.

In that way, we could add an `umpire force` - `Game Control` entry that has `Controls all (Green)` in the `Controls` drop-down.

Have I explained the above sufficiently well?

**Comment by ShendMikullovci** [comment]
> Have I explained the above sufficiently well?

I think so.

> I _was_ expecting the control to go into the `Forces` tab. So, on the `Green` force page, it would have `Controlled by` with a drop-down value of `Umpire` force.

From the Forces tab perspective, we could get something like this: 

![Controlled By feature 2](https://user-images.githubusercontent.com/85491794/169848501-8d86194d-6af2-4c66-9084-fd37999efaee.png)

If multiple members of White Force should be able to control Green, we could also use chips:

![Controlled By feature](https://user-images.githubusercontent.com/85491794/169848643-720b9019-bd54-4fbf-a387-4f06a4bbd2c5.png)


> We're half-way through letting different roles in a force control different assets #1531. For the second part of that, we need to add a "controls" drop-down, which is a drop-down of the assets in that force, plus "Controls none" and "Controls all". We _could_ modify that list to include assets from other forces, plus `Controls all (Blue-1)`, `Controls all (Green)`, and so on.
> 
> In that way, we could add an `umpire force` - `Game Control` entry that has `Controls all (Green)` in the `Controls` drop-down.

Channel Perspective: 
How about a "Can control other Forces" feature to the Force --> Roles tab?:

![Controls Other Forces](https://user-images.githubusercontent.com/85491794/169861835-fa607fce-aab1-4d38-865e-31e1bbed5cea.png)

Since the feature in this example is turned on, GC would have full access to each specific asset already available, as well as all/none in the Channels tab.

![Controls Other Forces 2](https://user-images.githubusercontent.com/85491794/169862464-eb4c29f4-ddfb-4eda-b6eb-48cd93777f7a.png)

Different icons we could work with:
![People Roof Icon](https://user-images.githubusercontent.com/85491794/169862556-5fcb6a46-e630-4be6-8797-1b53d4cc256c.png)
![Users Line](https://user-images.githubusercontent.com/85491794/169862574-689a04b3-7a96-4d67-a0d0-c8f2950be779.png)
![Users Gear](https://user-images.githubusercontent.com/85491794/169862593-61cfc561-7239-4b53-89d2-fc536fedb276.png)
![Users](https://user-images.githubusercontent.com/85491794/169862611-209b96fe-41df-4971-a321-8177711368bb.png)

What do you think?

**Comment by IanMayo** [comment]
Here is what the current draft implementation looks like:
![image](https://user-images.githubusercontent.com/1108513/169862997-e13ee89d-d4a9-40b4-b281-5c52d2aa3cfb.png)

The Blue role titled `Nort-CO` can control the asset called `NORT` from force `Blue-1 Force`.

Here the `CO` role for `Blue` can control all remaining `Blue` assets.

![image](https://user-images.githubusercontent.com/1108513/169863623-71156388-176f-421e-9bef-e5aa4a80cbc2.png)


If I just extend the assets list to include assets for other forces, plus a `Control-all` for each force - we can indicate which roles can control which assets, either by individual asset, or for a whole force.

**Comment by ShendMikullovci** [comment]
> If I just extend the assets list to include assets for other forces, plus a `Control-all` for each force - we can indicate which roles can control which assets, either by individual asset, or for a whole force.

Perfect. Looks good for me.
Do we want to provide this option for other games moving forward? If so, then the "Can control other forces" feature in the 
Forces --> Roles tab wouldn't be necessary.

**Comment by IanMayo** [comment]
>  then the "Can control other forces" feature in the Forces --> Roles tab wouldn't be necessary.

Correct, we won't need that role permission.

**Comment by IanMayo** [comment]
Closing. We've implemented per-role control of other force assets.
