### ISSUE TITLE
Blue Screen Triggered on Mapping Channel

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1626]
https://user-images.githubusercontent.com/85491794/174982202-e6c34a47-36cd-44b1-a006-a6c2276a6f84.mp4

**Comment by IanMayo** [comment]
Great - thanks for spotting that @ShendMikullovci 

But, that's still an April 2022 build. It may have been fixed.  I think it's worth only reporting bugs on recent builds - otherwise we may end up re-investigating issues that have been investigated/fixed already.

I know we haven't been giving you easy access to live builds (since Heroku has been down), but the `Releases` page now offers some up-to-date builds: https://github.com/serge-web/serge/releases

**Comment by IanMayo** [comment]
I'm closing this, since I've done lots and lots of work on the mapping component since April - and expect this will have been resolved.
