### ISSUE TITLE
Enumerated attribute values

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1676]
As a ***Game Control*** I wish to ***enumerated attribute values*** in order to ***improve attribute usability***

For a future wargame (WATU) the depth of submarines will be significant - and should be an attribute.

While we could allow players to enter a depth in metres, it would be better allow them to choose one of `Deep`, `PD` (short for _Periscope Depth_ and `Surface`.

We'll have to make this change both in how attributes are specified (in platform types) and how they are edited (in the attribute editor).

For attribute specification we'll need a new drop-down for the attribute. It will contain "Number" or "Strings".  If "Strings" is selected, then we'll have to allow the Game Designer to enter multiple values, plus the default value.  

For the editor we'll provide a drop-down list of values.

Maybe @ShendMikullovci 's existing design documents are available, and we can extend them to support the new functionality.

**Comment by ShendMikullovci** [comment]
Hi Ian! Excited about this.
I was wondering though, is depth really an attribute? It sounds like a "state" or "condition" to me to some degree (thinking back to the debate we had on attribute definition). Depending on what we think it is, we can present it in different ways. 

We could show it in a separate box: 

![Depth 1](https://user-images.githubusercontent.com/85491794/179423438-7f74befd-e0a6-4aed-a0c7-ad142a725532.png)

Toggle buttons for the 3 options, plus the possibility to add more options. You'll also notice I did some tidying up of the entire page (reduced the box sizes for other features and compacted them since now we're adding a new one). 

We could also have it shown as a fixed attribute: 

![Depth 2](https://user-images.githubusercontent.com/85491794/179423522-c86b5f18-dd78-4f64-b394-41e3a6226cc7.png)

Something we need to think about is that we might have to let SERGE know when this feature is appropriate (i.e., when asset travels by sea). Land/Air assets would automatically either have one less box, have the box greyed out, or have no fixed attribute. That is, only if we want to maintain attribute structure. If we want another UX entirely, then we can come up with something else (like opting for a list, similar to other channels, with more toggles and radio buttons, checkboxes, etc.). Let me know if you want me to try things out in that thoughtframe.

**Comment by IanMayo** [comment]
Thanks for exploring the idea.  Depth only relates to submarines, and they're not present in all wargames.  So, right now it doesn't seem justified to add it as a dedicated attribute.

Adding it as one of our custom attributes is the flexibility the users wanted.  If, one day, SERGE has to understand/use the concept of depth we can use one your mechanisms for adding it as a permanent attribute.

One observation on your second demo.  The Game Designer needs to indicate that it is a `string` value, and not a `number` value.  To allow us to grow the range of types the future, I think this should be a drop down list.  If we can, we also need to show the range of values in the `Attributes table` - so the Game Designer can review/check the available attributes.  This is in addition to the `default` value (`Deep` in our example).

Aah, actually... We don't use `Format` for string values. _Somehow_ we could present the list of available options in the that column.

Happy to talk it through further..

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - I'm starting to work on the backend changes for this, including making some test data.

I realise the two different types (number vs enum) will have different columns.  We _could_ handle this in one table by some columns having a different meaning depending on if its a enum or number atttribute.  But, on reflection I think it could be easier all round if we have two tables: one for number attributes (as with the current one), and another for enum attributes - with dedicated columns.

**Comment by ShendMikullovci** [comment]
Not sure if I fully understood, but I gave it a go. Did you mean something like this: 

https://user-images.githubusercontent.com/85491794/180102864-b13c180f-ab63-452a-accd-323a62f6cdb7.mp4

Obviously, clicking on Add Value Here would allow the user to type in the value, instead of having Periscope Depth pop up.

**Comment by IanMayo** [comment]
Yes, _kind-of_ like that.

But, if we can handle the layout issues, I'd like both sets to be within a single `Attributes` block.    First number attributes, then enumerated attributes.

For the enumerated issues, I think we'll need these columns:
- name
- editable by player (toggle)
- description
- values (popup list editor)
- default (drop-down list of values)

**Comment by ShendMikullovci** [comment]
Do we have a deployment for this? If we want to add those columns, we should consider rearranging the page to fit everything.

**Comment by ShendMikullovci** [comment]
Just saw the deployment. Great work!
