### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1688]
Hi everyone!

The game crashed when I clicked on the exit button on the top right. Was hit with a blue screen and I couldn't log into any game for a while, because the game list was erased entirely. I'm back in after a short delay (around 5-10 mins). I also checked the admin pages, and the game list disappeared there as well.

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - I can't be 100% sure on this, but this behaviour can happen if the "Heroku" hosting has gone to sleep.   When this happens, Serge in your browser will still be working, but the backend will no longer be responding.

If you do a "Refresh" on the page, and things work ok, then it's because of this "going to sleep" issue.

**Comment by ShendMikullovci** [comment]
Hi Ian! Hmmm. Refreshing the page didn't put everything back to place unfortunately. I only had to wait a little bit and it picked up where it left off.

**Comment by IanMayo** [comment]
Sure, OK.  If the issue is repeatable, could you give us the steps to repeat it please?

**Comment by ShendMikullovci** [comment]
https://user-images.githubusercontent.com/85491794/180755084-06979bcb-2ed4-4f84-9f01-590bf2c22743.mp4

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - could you have another go at reproducing this please?  I've been using `exit wargame` lots of times in recent weeks, without any problem.

**Comment by ShendMikullovci** [comment]
Seems to have been resolved. I'll let you guys know if it happens again.
