### ISSUE TITLE
Invisible Lists

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1983]
Hi everyone!

Noticed this small bug: 

https://user-images.githubusercontent.com/85491794/198851291-91049c53-4634-4a4c-80c0-7e9e680630d1.mp4

The lists seem to be invisible for all the features. The one under "Type" won't open.

**Comment by ShendMikullovci** [comment]
Question: I minimized the New Question tab and it disappeared. Does that mean the action was canceled?

**Comment by ShendMikullovci** [comment]
Also, canceling a message doesn't seem to put the window in a default state, rather it stays under "Land Activity": 

[de298c73-8e89-4271-99b6-e6980eea8415.webm](https://user-images.githubusercontent.com/85491794/198851420-990b05c2-a4a8-46e6-bc19-7e1a775277b8.webm)

**Comment by IanMayo** [comment]
Ok.  The "empty lists" is because the template for `land activity` doesn't currently match the content of the object we're providing. So, the editor form tries to create controls "on the fly".

But, your second issue is valid.  When the user presses `Cancel`, then we should wipe the form (and clear the form contents from the cache).  Can you look into this please @lilitkarapetyan ?

**Comment by lilitkarapetyan** [comment]
> Ok. The "empty lists" is because the template for `land activity` doesn't currently match the content of the object we're providing. So, the editor form tries to create controls "on the fly".
> 
> But, your second issue is valid. When the user presses `Cancel`, then we should wipe the form (and clear the form contents from the cache). Can you look into this please @lilitkarapetyan ?

Hello Ian, I will look into it.

**Comment by IanMayo** [comment]
Fixed
