### ISSUE TITLE
Drop-down lists for columns in `Orders` table

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2129]
For the `Orders` table we just have free-text filters for the columns. Some of these should be drop-down lists - particularly `author/role` and `activities`.

The code is in `PlanningMessagesList`.  Well ,it's in the call to `genData.toColumn()`.  I can see that we're collating the data for the `lookup`, but they don't seem to work in the app.

Can be tested in this story:
http://localhost:6611/?path=/story/local-organisms-planningmessageslist--default

**Comment by IanMayo** [comment]
Aah, there is a new issue here. 

If the contents of the table change (such as receiving a new orders object), the drop-downs do not update.  We do not want to replace the full set of columns for the table (since that would lose sort, selection, filter).  But, we do want to change some of the metadata for specific columns.  _Hopefully_ we can do that.  _Hopefully_ we can compare the new metadata with the existing metadata, and only update when necessary.

Steps to reproduce:  log in as blue player, with game in `planning` phase.

Look at existing `activities` in the orders, and choose one that isn't currently present (such as air patrol).

Create an air-patrol set of orders - enter shapes.  Provide a title for the orders, and `submit`.  The new orders will show on the table. But, the `activity` won't be in the metadata.  So, the activity isn't shown in the table. It also isn't available as the drop-down list for `activity`. 

If we F5 refresh the page, then the new activity will be `caught` and things will work ok.

So, in `planning-messages-list` - I don't think we should call `toColumn` and get all of the columns. That logic should probably be in `planning-messages-list`. If columns are zero, then generate the columns.  Then we get the `role` and `activity` metadata.  Then examine the relevant columns, and update the lookups if they are different to the current ones.

**Comment by lebaphi** [comment]
Hi @IanMayo, I see what you mean but I'm not sure we can implement this because the renderer happens at the react library level.

So for ease of understanding, react uses the term virtual dom (https://reactjs.org/docs/faq-internals.html) and the Diffing algorithm (https://reactjs.org/docs/reconciliation.html #the -diffing-algorithm), it will compare 2 elements (virtual dom vs internal dom), calculate the changes and update only the changed properties.

In development, we can calculate column data changes but to show the changes in UI we have to call setState(columns). We can do this if each column filter is a separate component then we can reduce the scope to render, but the material table requires the whole `columns= {columns}` so we have to set the whole columns (with parts metadata changes). At the library level react will only compute and update the changed properties.

So in our situation: 
- I think we can store the current filter/sort/select state before updating the new columns and then restoring it.
- find a way to customize the column filter, each column filter is a separate component then we can do what we want.

**Comment by IanMayo** [comment]
Sure - let's try the first one :-)

I thought we had an example of changing columns `live`, but I can't find it now. I must be mistaken.

**Comment by lebaphi** [comment]
okay, ahh i'm not quite clear about the steps to reproduce. I logged in as blue player and in order tab, I can't find the air patrol 🤔 

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/26705621/218450226-6835438f-933b-4487-87e0-e80ae7e0791c.png">

**Comment by IanMayo** [comment]
No, not done. I don't think we're updating the drop-down lists after new data is received.

Test using this:
- log in as blue player, in planning phase
- create a new set of orders. From the `Order Drawing` drop-down menu select an `Activity` that isn't currently present in teh Orders table
- the blue form will popup. Give it a date/title and `Submit`.  The new orders will be shown in the table. The drop-down list for `Activity` will not show the new item.
