### ISSUE TITLE
UI testing - phase 3

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2757]
This next phase of testing is Game- play 1, that we fill in the required fields, the message gets sent, and is then displayed.  It's also important to test that another logged in player gets the update too.

![image](https://github.com/serge-web/serge/assets/107697044/9790db2e-b4f0-4509-8bca-68d5c919645a)

Steps :
1. Play game with role White - Game Control
2. From 'Red-HQ' tab, send new message 1
3. Verify the message 1 is sent
4. From 'Blue-HQ' tab, send new message 2
5. Verify the message 2 is sent
7. Login game play with role Red - CO
8. Verify the message 1 is show on channel 'Red-HQ' 
9.  Login game play with role Blue - CO
10. Verify the message 2 is show on channel 'Blue-HQ' 
11. Send a message 3 as admin
12. Verify all user role can see the message 3

**Comment by IanMayo** [comment]
Yes @Tristina1788  - that's all good.

In a separate test, could we also include these please:
- login as blue player
- send feedback message
- send game admin message
- verify new admin message shown
- login as game control
- verify feedback shown (since that tab is only visible to Game Control)

Feedback is the left-hand icon in the admin section:
![image](https://github.com/serge-web/serge/assets/1108513/c2262ce9-dc29-4df1-afb6-f354823f1f5f)

Game Admin is the other tab in the admin section. Messages are sent using the input box at the bottom:
![image](https://github.com/serge-web/serge/assets/1108513/5d359771-94f8-4e62-ac42-9cb2864cf8e1)
