### ISSUE TITLE
Lost screen space

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2999]
The properties tab in the MappingPanel is missing some screen space at the bottom:
![Screenshot 2024-07-17 at 12 21 17](https://github.com/user-attachments/assets/4df01a12-e112-4222-9400-fda465144af0)

**Comment by Tristina1788** [comment]
@IanMayo @lebaphi I think  the reason is you click on the item which this user doesn't have permission for update properties ('Edit/remove Feature') .  
With current code on brach `2996-separate_add_remove`, user doesn't have permission updating properties will has button 'Cancel'. Click 'Cancel' same with action de-select item.

**Comment by IanMayo** [comment]
Aaah, of course.  In that case there isn't an issue 😀

**Comment by Tristina1788** [comment]
> Aaah, of course. In that case there isn't an issue 😀

Yes, I think so.
