### ISSUE TITLE
Switch Channels to array from dictionary

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#617]
Array processing is easier to maintain (& maybe understand) than dictionaries.

The `PlayerUIChannels` object is a dictionary. We should switch it to an array, for tidier processing.

**Comment by sanjayradadiya** [comment]
Currently we are storing `uniqid` of channel as object key and i am sure that those object would be used every in the app like to get specific channel from object using `channel[uniqi]`  so if we used array there then if we need to find specific channel from list then we need to again write find method and that will retrieve specific channel from array lists. 

Here my question is why really we need to make this changes because after that we are loosing above scenario where we will get specific channel easily just using `channel[uniqi]`. 😕

**Comment by IanMayo** [comment]
Ok, thanks @sanjayradadiya  - good advice.

Closing issue.
