### ISSUE TITLE
Introduce `Mark message as unread`

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#903]
While some players skim through all new messages, they may wish to highlight some that still require some action from them.

They could do this if we offered `mark message as unread` support.  This would clear the `read` cookie for that message.

A Natural UI element for this would be the dark-blue `Read` indicator.  Clicking on it would collapse the message, and clear the read flag:

![image](https://user-images.githubusercontent.com/1108513/124171578-a9017680-daa0-11eb-99ca-68816081c90e.png)

**Comment by IanMayo** [comment]
@lebaphi - I welcome @ShendMikullovci contributing his thoughts on this user interaction.

A _playable_ version of the above wargame is here:  https://serge-review.herokuapp.com/?wargame=wargame-kqgy546g&access=pkoiqu5ev

I have a _slight_ worry that the dark blue circle is a small click target, plus is a "hidden interaction" - there aren't any visual clues that the user can mark as unread by clicking it.  We _could_ include this guidance in the intro walkthrough - but I feel we can't rely on that.

**Comment by ShendMikullovci** [comment]
Great feature. The first thing that came to mind was the Gmail feature for read and unread emails. Gmail highlights unread emails to a bright grey and the read ones are kept in a dimmer and darker shade of grey, similar to our feature with lighter and brighter blue messages for the unread messages, and dimmer for the read ones. 
Gmail also suggests a “Mark as Read/Unread” button for each email: 
![GMAIL UNREAD MESSAGE FEATURE](https://user-images.githubusercontent.com/85491794/124259929-63d85580-db2f-11eb-89e5-a06d44af517f.png)

The button is an open envelope to mark the email as read, and a closed one to mark it as unread. It’s a comprehensive, simple, and straightforward way to keep track of your inbox.

It could be beneficial to add a similar feature to SERGE. I went through our Icon library and found the following: 
![READ-UNREAD MESSAGE FEATURE ENVELOPPE ICON](https://user-images.githubusercontent.com/85491794/124259975-70f54480-db2f-11eb-8696-120c85a32243.png)

It could also be interesting to use bold colors for the unopened messages, to highlight their importance and direct attention, and dimmed colors for the opened ones to reduce attentional clutter.
An important thing to consider is, once we would add this feature if we’d keep the “UNREAD” feature alongside the envelope icon. It could add unnecessary clutter to the visual display.

An alternative set of icons could be the following:
![READ-UNREAD MESSAGE FEATURE COMMENT ICON](https://user-images.githubusercontent.com/85491794/124260032-81a5ba80-db2f-11eb-912e-9c9170f9021b.png)

We could use the same logic with these different comment icons, keeping the bright, bold colors for the unread messages, and the dimmer ones for the read ones. This comment icon fits the description as well, given that it’s commonly used to indicate chat or chatrooms across apps online. 

However, the term “chat” has a more social, almost recreational ring to it so it’s important to know beforehand what kind of messages would be circulating in order to know whether the comment icon would match the importance and seriousness of the messages.

Let me know what you guys think.

**Comment by IanMayo** [comment]
That's a fantastic idea @ShendMikullovci 

We could replace the light/dark blue circles with the open/closed message marker.

@ShendMikullovci - you'll see that messages 2 and 4 in the screenshot are shown in more suppressed colors.

If you have some other formatting strategy in mind, I'm happy to hear it.

**Comment by ShendMikullovci** [comment]
Yes, messages 2 and 4 illustrate this principle. 
A detail that might go a long way is to dim the white segment on the side of the read messages like so:
![READ MESSAGES GREY SIDE SEGMENT](https://user-images.githubusercontent.com/85491794/124290442-b88dc780-db53-11eb-9521-a64bb88079c5.png)

This further emphasizes the bright/dim logic and brings more attention to unread messages. 
Coupled with the envelope/comment icon (depending on which we select), the side segments would switch colors depending on the state (read/unread) the user decides to leave the message in.

**Comment by ShendMikullovci** [comment]
It would look something like this: 
![MESSAGE READ UNREAD](https://user-images.githubusercontent.com/85491794/124293042-86319980-db56-11eb-811c-14649c6af3f7.png)

P.S. Excuse the ugly icons, I suck at coding.

**Comment by lebaphi** [comment]
I just wonder if we have the icon indicator, do we need the yellow label UNREAD ?

**Comment by lebaphi** [comment]
agree, the icons don't look polished @ShendMikullovci 😂

**Comment by IanMayo** [comment]
Hello @lebaphi - yes, I endorse @ShendMikullovci 's design thoughts:
1. For `read` messages, make the side-bar semi-transparent.  60%?
2. Display `unread` and `read` markers, using `envelope` and `envelope-open`.  `Read` marker has `Click here to mark as unread` tooltip.  Clicking on a `Read` marker switches message to `Unread` status.

**Comment by lebaphi** [comment]
Hi @IanMayo , do you mean to make this sidebar more transparent for `read` messages ?
![image](https://user-images.githubusercontent.com/26705621/125155839-83edc180-e18c-11eb-95ae-b4c44e19f351.png)

**Comment by IanMayo** [comment]
Yes, the vertical line.

**Comment by lebaphi** [comment]
@Fixed @IanMayo 👍
