### ISSUE TITLE
Channel template conflict for multiple role and multiple channel.

### ISSUE THREAD

**Issue by sanjayradadiya** [serge-web/serge#994]
## 🐞 Bug description

https://user-images.githubusercontent.com/16476120/129512377-17145f86-0d4a-4c6a-8e9f-99972af2dfce.mov
1. template set for the channel is not displayed.
2. wrong role name display.

## 💻 System information

 - Operating System: [e.g. iOS, Windows, etc...]
 - Browser Version [e.g. 22]
 - Browser resolution 
 - Are cookies enabled
 - Is Javascript enabled
 - Do you have an ad blocker

**Comment by IanMayo** [comment]
Thanks for this @sanjayradadiya 

It would be useful to have a copy of `Papa Foxtrot` to test this. Could you create a PR for #988 that contains the new wargame please?

**Comment by IanMayo** [comment]
Ok. I think we established that this was because the same `pass-code` was being used for two roles.

So, in the code where we create a new role (and pass-code) we need to call a helper function that checks no other role is already using that passcode.  If it's in use, generate another and repeat the above.

**Comment by IanMayo** [comment]
Close. Handled in #994
